# Generated by Django 5.1.4 on 2024-12-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teavarity',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teavarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
