# Generated by Django 5.1.4 on 2024-12-17 03:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_teavarity_desc_teavarity_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('tea_varieties', models.ManyToManyField(related_name='stores', to='polls.teavarity')),
            ],
        ),
        migrations.CreateModel(
            name='TeaCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issued_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_date', models.DateField()),
                ('tea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='polls.teavarity')),
            ],
        ),
        migrations.CreateModel(
            name='TeaReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating should be between 1 (lowest) and 5 (highest).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='polls.teavarity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
